import Head from "next/head";
import { Footer } from "../components/Footer";
import Header from "../components/Header";
import { Hero } from "../components/Hero";
import { ProjectsSection } from "../components/ProjectsSection";

// import { Header } from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andre Jarboe Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <ProjectsSection />
      <Footer />
    </div>
  );
}

export const gerServerSideProps = async () => {
  const query = `*[_type == "project"]{
    _id,
    title,
    slug,
    description
  }`
}
